[package]
name = "vmf"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = "0.10"
logos = "0.15"
memmap2 = "0.9"
thiserror = "2.0"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "versioninfo"
harness = false

[[bench]]
name = "color"
harness = false

[[bench]]
name = "visgroups"
harness = false

[[bench]]
name = "viewsettings"
harness = false

